In [2]:
import numpy as np
import pandas as pd

In [11]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [12]:
def mae(y_true, y_predicted):
    total_error = 0
    
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
        
    print('Total error: ', total_error)
    
    mae = total_error / len(y_true)
    print('MAE: ', mae)
    return mae

In [13]:
mae(y_true, y_predicted)

Total error:  2.5
MAE:  0.5


0.5

In [14]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [15]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [16]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [19]:
np.log([0.000000000000000001])

array([-41.44653167])

In [20]:
eplison = 1e-15

In [21]:
y_predicted

array([1, 1, 0, 0, 1])

In [22]:
y_predicted_new = [max(i, eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]