In [2]:
import torch

# Model Parameters

In [5]:
w_1 = torch.tensor([0.23], requires_grad = True)
b = torch.tensor([0.1], requires_grad = True)

# Inputs & Target

In [6]:
x_1 = torch.tensor([1.23])
y = torch.tensor([1.])

In [8]:
u = x_1 * w_1
z = u + b

print(z)

tensor([0.3829], grad_fn=<AddBackward0>)


In [9]:
a = torch.sigmoid(z)

In [10]:
a

tensor([0.5946], grad_fn=<SigmoidBackward0>)

In [12]:
import torch.nn.functional as f

In [13]:
l = f.binary_cross_entropy(a, y)
l

tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)

In [17]:
 # Best Practice! 

import torch.nn.functional as f

l = f.binary_cross_entropy_with_logits(z, y)
l

tensor(0.5199, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [18]:
from torch.autograd import grad

In [19]:
grad_L_w1 = grad(l, w_1, retain_graph = True)
grad_L_w1

(tensor([-0.4987]),)

In [20]:
grad_L_b = grad(l, b, retain_graph = True)
grad_L_b

(tensor([-0.4054]),)

# .backward()

In [21]:
l.backward()

In [23]:
w_1.grad

tensor([-0.4987])

In [24]:
b.grad

tensor([-0.4054])