In [1]:
import torch

In [5]:
"""
class MyClassifier(torch.nn.Module):
    def __init__(self):
        # define Model Parameters

    def forward(self, x):
        # Define how the model
        # produces outputs

        return

model = MyClassifier()
optimizer = torch.optim.SGD(...)

for epoch in range(num_epochs):
    for x, y in train_dataloader:

        # forward pass
        outputs = model(x)
        loss = loss_fn(outputs, y)

        # backward pass (backpropagation)
        optimizer.zero_grad()
        loss.backward()

        # update model parameters
        optimizer.step()

"""

'\nclass MyClassifier(torch.nn.Module):\n    def __init__(self):\n        # define Model Parameters\n\n    def forward(self, x):\n        # Define how the model\n        # produces outputs\n\n        return\n\n'

# Neural Network Layers

In [6]:
import torch

In [7]:
torch.manual_seed(123)

linear = torch.nn.Linear(in_features = 2, out_features = 1)

In [8]:
linear.weight

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)

In [9]:
linear.bias

Parameter containing:
tensor([-0.3512], requires_grad=True)

In [10]:
# single training example
x = torch.tensor([[1.2, 0.5]])
x

tensor([[1.2000, 0.5000]])

In [12]:
w = linear.weight.detach()
b = linear.bias.detach()
z = x.matmul(w.T) + b

z

tensor([[-0.6855]])

In [14]:
x = torch.tensor([[1.2, 0.5],
                  [0.7, 0.8],
                  [0.1, 0.2]]) # 3 training example

x

tensor([[1.2000, 0.5000],
        [0.7000, 0.8000],
        [0.1000, 0.2000]])

In [16]:
z = x.matmul(w.T) + b

z

tensor([[-0.6855],
        [-0.5343],
        [-0.3753]])

In [17]:
z = linear(x)

z

tensor([[-0.6855],
        [-0.5343],
        [-0.3753]], grad_fn=<AddmmBackward0>)