# Creating Tensors

In [30]:
import torch

In [31]:
m = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

# Checking the Shape

In [32]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
m.shape

torch.Size([2, 3])

# Checking the Rank / Number of Dimensions

In [34]:
m.ndim

2

# Checking the Data Type

In [35]:
m.dtype

torch.float32

In [36]:
other_m = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

In [37]:
other_m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
other_m.dtype

torch.int64

# Creating a Tensor from Numpy Arrays

In [39]:
import numpy as np

In [40]:
np_ary = np.array([1., 2., 3.])
m2 = torch.from_numpy(np_ary)

m2

tensor([1., 2., 3.], dtype=torch.float64)

# Changing Data Types

In [41]:
m2.dtype

torch.float64

In [42]:
m2 = m2.to(torch.float32)
m2.dtype

torch.float32

# Checking the Device Type

In [43]:
m2.device

device(type='cpu')

# Changing the Tensor Shape

In [44]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [45]:
m.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [46]:
m.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

# Transposing a Tensor

In [47]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [48]:
m.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

# Multiplying Matrices

In [49]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.]])